ci:
  extends: ./.lighthouserc.yaml
  collect:
    settings:
      preset: desktop
      # Override every mobile setting inherited from the base configuration.
      formFactor: desktop
      screenEmulation:
        mobile: false
        width: 1350
        height: 940
        deviceScaleFactor: 1
        disabled: false
  upload:
    outputDir: ./lighthouse-reports/desktop
