name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  MISE_LOCKED: "1"
  MISE_LOCKED_VERIFY_PROVENANCE: "1"

jobs:
  deploy:
    environment:
      name: production
      url: ${{ vars.DEPLOY_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout content repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Pugma/blog-content
          path: ./src/content/posts
          token: ${{ secrets.BLOG_CONTENT_GITHUB_PAT }}

      - name: Setup mise
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@953926a2e2182532811c01a25e53647d93bf07c0 # v4.1.3
        with:
          command: deploy
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
